# Generated by Django 3.2.9 on 2022-01-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddConstraint(
            model_name='friend',
            constraint=models.UniqueConstraint(fields=('user', 'friend'), name='unique_friend'),
        ),
    ]
